# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning

name: build and deploy container app to Web App - digittech-service
on:
  push:
    branches:
      - hw-dev-cred
      - hw-staging
      - hw-prod
    paths-ignore:
      - deployment.yaml
  pull_request:
    branches:
      - hw-dev-cred
      - hw-staging
      - hw-prod
    paths-ignore:
      - deployment.yaml
  workflow_dispatch:

jobs:
  # Build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   environment: dev

  #   env:
  #     NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
  #     NEXT_PUBLIC_SMART_USER_API_URL: ${{ secrets.NEXT_PUBLIC_SMART_USER_API_URL }}
  #     NEXT_PUBLIC_BACKOFFICE_URL: ${{ secrets.NEXT_PUBLIC_BACKOFFICE_URL }}

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2

  #   - name: Setup pnpm
  #     uses: pnpm/action-setup@v2
  #     with:
  #       version: 8

  #   # Verify pnpm is available
  #   - name: Check pnpm version
  #     run: pnpm -v

  #   # Install dependencies
  #   - name: Install dependencies
  #     run: pnpm install

  #   # Run ESLint
  #   - name: Run ESLint
  #     run: pnpm lint

  #   # Run TypeScript type check
  #   - name: Run TypeScript type check
  #     run: pnpm typecheck
  Build:
    name: Build
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2


  Deploy-to-Dev:
    if: github.ref == 'refs/heads/hw-dev-cred'
    name: Deploy-to-Dev
    runs-on: ubuntu-latest
    needs: Build
    environment: 
     name: dev
     url: https://digittech-dev.credlanche.com
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log in to Huawei Cloud SWR
      uses: huaweicloud/swr-login@v2.1.0
      with:
        access-key-id: ${{ secrets.HW_ACCESS_KEY }}   # Must have created a github secrets containing the access key.
        access-key-secret: ${{ secrets.HW_SECRET_KEY }}   # Must have created a github secrets containing the secret key
        region: af-south-1

    - name: Build and push Docker image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --provenance=false \
          -t swr.af-south-1.myhuaweicloud.com/cred-dev/digittech-service:${{ github.sha }} \
          --push .


    - name: Configure kubectl for Huawei Cloud CCE    ##Must have created a github secrets containing the kubeconfig
      run: |
        sudo mkdir -p $HOME/.kube
        sudo chown -R runner:runner $HOME/.kube
        export KUBECONFIG=$HOME/.kube/config
        echo "${{ secrets.KUBE_CONFIG_DATA }}" > $KUBECONFIG    
    - name: Update deployment
      run: |    # Updates the deployment.yaml to you the latest  build
        sed -i "s@swr.af-south-1.myhuaweicloud.com/cred-dev/digittech-service:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/cred-dev/digittech-service:${{ github.sha }}@g" deployment.yaml    

    - name: Deploy to Huawei CCE
      run: |    # Run your kubectl commands here
        kubectl apply -f deployment.yaml

  notification:
    name: Notify to Teams
    runs-on: ubuntu-latest
    needs: Deploy-to-Dev
    steps:
      - name: Notify Microsoft Teams
        if: always()
        run: |
          curl -H 'Content-Type: application/json' \
            -d '{
                  "@type": "MessageCard",
                  "@context": "http://schema.org/extensions",
                  "summary": "Deployment Notification",
                  "themeColor": "0076D7",
                  "sections": [{
                    "activityTitle": "🚀 Deployment Status: '${{ needs.Deploy-to-Dev.result }}'",
                    "facts": [
                      { "name": "Repository", "value": "${{ github.repository }}" },
                      { "name": "Actor", "value": "${{ github.actor }}" },
                      { "name": "Branch", "value": "${{ github.ref_name }}" },
                      { "name": "Commit Message", "value": "${{ github.event.head_commit.message }}" },
                      { "name": "Commit", "value": "[View Commit](${{ github.event.head_commit.url }})" }
                    ],
                    "markdown": true
                  }]
                }' \
            ${{ secrets.MSTEAMS_WEBHOOK }}
          
  if_failure:
    name: Only if failure
    runs-on: ubuntu-latest
    needs: Deploy-to-Dev
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}

  manual-approval-staging:
    if: github.ref == 'refs/heads/hw-staging'
    name: Manual Approval to staging
    runs-on: ubuntu-latest
    needs: Build
    #if: success() # Only proceed if terraform-plan job succeeds
    
    permissions:
      issues: write

    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: "Superseun99,supermanng" # Replace with GitHub usernames, with the free version you can only have an issue assigned to one username
          minimum-approvals: 1
          issue-title: "Manual Approval Required to staging"
          issue-body: "Please approve or deny the deployment."

  Deploy-to-staging:
    if: github.ref == 'refs/heads/hw-staging'
    name: Deploy-to-staging
    runs-on: ubuntu-latest
    needs: manual-approval-staging
    environment: 
      name: staging
      url: https://digittech-staging.credlanche.com
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log in to Huawei Cloud SWR
      uses: huaweicloud/swr-login@v2.1.0
      with:
        access-key-id: ${{ secrets.HW_ACCESS_KEY }}   # Must have created a github secrets containing the access key
        access-key-secret: ${{ secrets.HW_SECRET_KEY }}   # Must have created a github secrets containing the secret key
        region: af-south-1

    - name: Build and push Docker image
      run: |
        docker build \
          --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
          --build-arg NEXT_PUBLIC_SMART_USER_API_URL=${{ secrets.NEXT_PUBLIC_SMART_USER_API_URL }} \
          --build-arg NEXT_PUBLIC_BACKOFFICE_URL=${{ secrets.NEXT_PUBLIC_BACKOFFICE_URL }} \
          -t swr.af-south-1.myhuaweicloud.com/cred-staging/digittech-service:${{ github.sha }} .
        docker push swr.af-south-1.myhuaweicloud.com/cred-staging/digittech-service:${{ github.sha }}

    - name: Configure kubectl for Huawei Cloud CCE    ##Must have created a github secrets containing the kubeconfig
      run: |
        sudo mkdir -p $HOME/.kube
        sudo chown -R runner:runner $HOME/.kube
        export KUBECONFIG=$HOME/.kube/config
        echo "${{ secrets.KUBE_CONFIG_DATA2 }}" > $KUBECONFIG    
    - name: Update deployment
      run: |    # Updates the deployment.yaml to you the latest  build
        sed -i "s@swr.af-south-1.myhuaweicloud.com/cred-staging/digittech-service:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/cred-staging/digittech-service:${{ github.sha }}@g" deployment-staging.yaml    


    - name: Debugging
      run: |
        kubectl version
        kubectl cluster-info
        kubectl get nodes

    - name: Deploy to Huawei CCE
      run: |    # Run your kubectl commands here
        kubectl apply -f deployment-staging.yaml

  manual-approval-prod:
    if: github.ref == 'refs/heads/hw-prod'
    name: Manual Approval to Prod
    runs-on: ubuntu-latest
    needs: Build
   # if: success() # Only proceed if terraform-plan job succeeds
    
    permissions:
      issues: write

    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: "Superseun99,supermanng" # Replace with GitHub usernames, with the free version you can only have an issue assigned to one username
          minimum-approvals: 1
          issue-title: "Manual Approval Required for staging"
          issue-body: "Please approve or deny the deployment."


  Deploy-to-prod:
    if: github.ref == 'refs/heads/hw-prod'
    name: Deploy-to-Prod
    runs-on: ubuntu-latest
    needs: manual-approval-prod
    environment: 
      name: prod
      url: https://digitvanttechnology.digitvant.com
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Huawei Cloud SWR
      uses: huaweicloud/swr-login@v2.1.0
      with:
        access-key-id: ${{ secrets.HW_ACCESS_KEY }}   # Must have created a github secrets containing the access key
        access-key-secret: ${{ secrets.HW_SECRET_KEY }}   # Must have created a github secrets containing the secret key
        region: af-south-1

    - name: Build and push Docker image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --provenance=false \
          -t swr.af-south-1.myhuaweicloud.com/cred-prod/digittech-service:${{ github.sha }} \
          --push .


    - name: Configure kubectl for Huawei Cloud CCE    ##Must have created a github secrets containing the kubeconfig
      run: |
        sudo mkdir -p $HOME/.kube
        sudo chown -R runner:runner $HOME/.kube
        export KUBECONFIG=$HOME/.kube/config
        echo "${{ secrets.KUBE_CONFIG_DATA2 }}" > $KUBECONFIG    
    - name: Update deployment
      run: |    # Updates the deployment.yaml to you the latest  build
        sed -i "s@swr.af-south-1.myhuaweicloud.com/cred-prod/digittech-service:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/cred-prod/digittech-service:${{ github.sha }}@g" deployment-prod.yaml    


    - name: Debugging
      run: |
        kubectl version
        kubectl cluster-info
        kubectl get nodes

    - name: Deploy to Huawei CCE
      run: |    # Run your kubectl commands here

        kubectl apply -f deployment-prod.yaml